# Generated by Django 3.1 on 2020-09-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Senior Doctor', 'Senior Doctor'), ('Health Expert', 'Health Expert')], default='Patient', max_length=30),
        ),
    ]
