# Generated by Django 3.1 on 2020-09-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_expertprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpertProfile',
        ),
    ]
