# Generated by Django 3.1 on 2020-10-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
