# Generated by Django 3.1 on 2020-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='approval1',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='approval2',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50),
        ),
    ]
