# Generated by Django 3.1 on 2020-10-03 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_auto_20201003_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
                ('address', models.TextField()),
                ('approval1', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('approval2', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('broad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.broad')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('narrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.narrow')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Booked', 'Booked')], default='Free', max_length=30)),
                ('docprof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='def.jpg', null=True, upload_to='images')),
                ('user_role', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Senior Doctor', 'Senior Doctor'), ('Health Expert', 'Health Expert')], default='Patient', max_length=30)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
                ('investigation', models.CharField(max_length=100)),
                ('examination', models.CharField(max_length=100)),
                ('docprof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.state'),
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schedule')),
            ],
        ),
    ]
