# Generated by Django 3.1 on 2020-10-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201003_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('broad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.broad')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_id', models.CharField(default='C100000', max_length=50)),
                ('broad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.broad')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.doctor')),
            ],
        ),
    ]
