# Generated by Django 3.1 on 2020-10-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='main.post')),
                ('post1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post1', to='main.post')),
                ('post2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post2', to='main.post')),
                ('post3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post3', to='main.post')),
                ('post4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post4', to='main.post')),
            ],
        ),
    ]
